### PR TITLE
Windows Dependencies

### PR DESCRIPTION
**Pull request by siteleas**
Here are some added instructions for getting Gitify to work on Windows

### CODE REVIEW

**Comment by Alroniks** [comment]
Thank you for your contribution @siteleas 
What do you think @Mark-H, should it be in the repo or we can add it to wiki and docs?

**Comment by Mark-H** [comment]
This should probably be added to this wiki: https://github.com/modmore/Gitify/wiki/1.1.-Installation-on-Windows

**Comment by siteleas** [comment]
Okay gents, I added the information from the .md to the docs page as Mark indicated. Thanks for all your efforts. I am not sure how many people do MODx development on Windows, but we primarily use Windows for development, even though many of our personal and business computers are loaded with Linux. I noticed some comments from some people that they didn't know how to get Gitify working on Windows, so I thought since I was able to, I would document it and submit it.

**Comment by Mark-H** [comment]
Thanks @siteleas! I have no idea how many people build on Windows either, but we get enough questions about it that it's worth thinking about... I just don't have the faintest idea on windows specific stuff, when I used windows for development my terminal /command prompt of choice was Git Bash, which seemed pretty close to the terminal on mac/linux when I got my first macbook so a lot of this is new to me ;)

**Pull request closed without merging**
