### PR TITLE
add params --config=file for modx:install command

### PR DESCRIPTION
**Pull request by tyllo**
Set option for command:
```
Gitify modx:install --config=path/to/config
```
- optional if in .gitify set block `config:` for  `path: path/to/config` 
- or set in `config:` params for config.

Available params in .gitify:
```
config:
    path: path/to/config
    modx_dir:
    table_prefix:
    database_type:
    dbase:
    database_user:
    database_password:
    database_server:
    modx_base_url:
    language:
    defaultMgrUser:
    managerPass:
    vmanagerEmail:
```

### CODE REVIEW

**Comment by Alroniks** [comment]
Can you explain about config in .gitify? This data will used once, when will be installed modx. Also store database user and password in this config is not good idea.
I have the similar idea with default config for local develoment environment. I mean database from homestead always use the same user and password, only different dbname. And my idea was store this config to /home/user/.gitify dir and pull them if needed.

**Comment by tyllo** [comment]
The idea is that you need to be hide .gitify like folder up in future, then you can set the password in it, but it does not hurt to specify not all params in .gitify

**Comment by Mark-H** [comment]
This looks similar to the idea in #48 except in this case you define the path to the config file, whereas in #48 the idea was a .gitifyrc file in the user root. While I can see uses for both, this looks a bit more flexible as the file could also be elsewhere.

**Comment by sebastian-marinescu** [comment]
Hi @tyllo why did you close it? 

I really like your idea, and actually think this could be combined with #48 for super flexibility. Don't you?

**Comment by tyllo** [comment]
Hey @sebastian-marinescu. When my work appeared ModX tried to make it more convenient to deploy the project and shared his idea. Now my work is far from ModX and I do not have time to help develop the idea.
P.S. Sorry for my English

**Comment by Mark-H** [comment]
This was automatically closed because the branch was removed on @tyllo's fork.. it could still be merged but that became a tad more difficult now.

**Comment by sebastian-marinescu** [comment]
Okay, thanks @tyllo and @Mark-H for explaining the situation :) 

I'll look into this and the _.gitifyrc_ concept soon and will get back with my thoughts and hopefully a nicely working solution. I will probably open a new issue and reference this and #48 in it.

**Pull request closed without merging**
