### PR TITLE
Fix Init command when Data and/or Backup directories already exists and are not empty

### PR DESCRIPTION
**Pull request by hansek**
It would be nice to have those two code blocks (getting of data and backup directory) in one cycle, because both are almost the same, there are only small differences.

Currently following only the original "habit" :)

### CODE REVIEW

**Comment by Mark-H** [comment]
Hmm I'm not sure why we need to prevent the user from continuing if the folder already exists, could you explain?

**Comment by hansek** [comment]
Because of PHP Warning which is shown if you try created directory by mkdir() and it already exists. :wink:

**Comment by Mark-H** [comment]
Yeah I get that, but what about this?

```` php
+            if (!$this->isEmptyDirectory($directory)) {
+                $output->writeln('<error>Error: Specified directory already exists and is not empty. Please enter different directory name or delete all the content of directory.</error>');
+                return 1;
+            }
````

Can't we just skip the mkdir, but allow the command to continue?

**Comment by hansek** [comment]
You are right Mark, someone might want to put Gitify data folder into project folder and then init Gitify.

PR altered.

**Comment by Mark-H** [comment]
Apologies @hansek - I just went through the PRs top to bottom and merged #128 without realising you had sent an earlier PR for the same problem. Either way, thank you for your contribution and making Gitify better!

**Comment by hansek** [comment]
Great is in Gitify ;) 

Have a few stuff to be fixed for proper work in Windows (etc https://github.com/hansek/Gitify/commit/eed4d51d5c0ed96ea0e0e64feebaa0fa859ed9d6). It needs to be more "thoughtful" to be consistently implemented in Gitify (generaly slashes in path). :wink: 

Thanks for your work Mark, Gitify is great :hammer:!

**Pull request closed without merging**
