### PR TITLE
Fix fallback Gitify-Cache-Folder

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
On my server I hit the last if condition. So Gitify tries to set the Gitify-Cache-Folder, named ".gitify", in the Gitify-Working-Dir, which also includes ".gitify" (the file). This failed, because the Gitify-Cache-Folder is the Gitify-Config-File.

This changes the Gitify-Cache-Folder to ".gitify-cache".

### CODE REVIEW

**Comment by Alroniks** [comment]
Hi @sebastian-marinescu 
Thank you for the pull request, but an issue in the other place. Goal was to make the same mechanism as in composer - put MODX archives to user home folder in special .gitify folder. So code in application work absolutely correct and this folder can be placed in gitify project root also.

But when trait DownloadModx try download modx it checks folder here https://github.com/modmore/Gitify/blob/master/src/Mixins/DownloadModx.php#L51 and the funtion file_exists returns false if file exists and destination folder for package will not created. So you see error. 
A fast fix - add additional check to this rule:
```php
if (!file_exists(GITIFY_CACHE_DIR) && !is_folder(GITIFY_CACHE_DIR)) {
    mkdir(GITIFY_CACHE_DIR);
}
```

**Comment by sebastian-marinescu** [comment]
Hi @Alroniks 
thanks for your input and the explanation. 
Added the fast fix and also checked if is_folder in the ClearCacheCommand.
What do you think? It's okay like that?

**Comment by Alroniks** [comment]
Hi @sebastian-marinescu 
Sorry for a delay and my wrong advice. I double checked your PR and all behavior and find a solution. I can fix it, but I thankful to you for help and I not want to lose your contribution. Your first thoughts were correct.
Please, remove `is_folder` from `ClearCacheCommand.php` and `DownloadModx.php`. Really in PHP exists only is_dir, but now it doesn't matter.
And add to 'application.php' code from 48 line:
```
$cacheDir = '.gitify';
if (is_file(implode(DIRECTORY_SEPARATOR, array($home, $cacheDir)))) {
    $cacheDir .= '-cache'; // need in case when home directory is the working dir of gitify also
}

define('GITIFY_CACHE_DIR', implode(DIRECTORY_SEPARATOR, array($home, $cacheDir, '')));
```

After this fix, gitify will check `.gitify` file in root and if it exists, then it will try to create `.gitify-cache` folder instead `.gitify`. It's strange, but the truth: in many systems folder also a file, but with some differences. So we cannot keep folder and file with the same name in one folder.

**Comment by sebastian-marinescu** [comment]
Hi @Alroniks and thanks for your reply!
I am very sorry for and embarrassed by is_folder - but you know....it was late :stuck_out_tongue_winking_eye: 
I'll change the PR in the next couple of days and commit the fix :+1:

**Comment by sebastian-marinescu** [comment]
Okay, I think this should be okay now, but I haven't tested it on the aforesaid server. 
Either you review it again, or I'll report back when I've tried it out :+1:

**Comment by sebastian-marinescu** [comment]
Hi @Alroniks I tested the fix on two projects and it works as expected. 
As I must use this fix on the servers I'm working I would love it, if we could merge this PR soon :shipit:

**Comment by sebastian-marinescu** [comment]
Thank you for merging! :)

**Pull request merged**
