### PR TITLE
Add option to package provider credentials can be defined with a file

### PR DESCRIPTION
**Pull request by hansek**

### CODE REVIEW

**Comment by hansek** [comment]
@Mark-H did you have a time to think about this? :)

**Comment by Mark-H** [comment]
I like it, just needs testing and the merge :) 

Have been trying to finish the modmore demo site (which needs this fix) but keep getting side tracked on other stuff. Hopefully I'll finally get to that tomorrow!

**Comment by hansek** [comment]
:+1:

**Comment by Mark-H** [comment]
Thanks @hansek - just had to add an import for the main Gitify class, has now been merged :)

**Comment by hansek** [comment]
Cool, thanks! :+1:

**Pull request merged**
