### PR TITLE
Added ability exclude element that installed with packages

### PR DESCRIPTION
**Pull request by Alroniks**
# What does it do ?
Exclude elements, that installed by package manager (matched by category). List of packages specified in packages section in config.

# Why is it needed ?
For keeping repo is clean. Example here https://github.com/alroniksteam/alroniks.com. Only site code.

# Troubles
Not all package elements use categories. For exclude rest you can use `where`  in config.
Example:
```
snippets:
        class: modSnippet
        primary: name
        extension: .php
        where:
            - 'name:!=': Markdown
    plugins:
        class: modPlugin
        primary: name
        extension: .php
        where:
            - 'name:!=': Ace
            - 'name:!=': ClientConfig
```

### CODE REVIEW

**Comment by Mark-H** [comment]
Awesomesauce!!

I can see one potential issue here though, and I'm wondering how you think we should handle that, which is that `Gitify build --force` will do a removeCollection on every object (as of https://github.com/modmore/Gitify/commit/d19a2443c4303145095a6c55395cae315212c5d8). So every element, for example, would be removed while only part of them are restored with the build.

**Comment by Alroniks** [comment]
Hm, good question. Probably build command should use config too. Or solve this issue by workflow.
1. `git pull`
2. `gitify build -f`
3. `gitify install:package --all --upgrade`

**Comment by Alroniks** [comment]
Now I am working on `gitify install:modx --upgrade`, and need some more tests.

**Comment by Mark-H** [comment]
Per 22ade32804b4be1f5b51d36cedc7c67096b6f39e, `Gitify install:package --all` (or when specifying a package) it will always install the last version of the package, effectively doing an upgrade. :D

**Comment by adamwintle** [comment]
This looks very interesting, I haven't tried the code yet, but could it also be used for something like:

```
content:
        type: content
        exclude_keys:
            - editedby
            - editedon
       where:
            - 'parent:=': 123
```
or
```
       where:
            - 'template:=': 99
```

To exclude certain un-wanted groups of resources from the data?

**Comment by Alroniks** [comment]
@adamwintle For content it's not work :) I tried. For content used another method, without processing `where` section

**Comment by Mark-H** [comment]
Per https://github.com/modmore/Gitify/commit/3380f9727be47e7fbd9ca9746aca10ec088374fe the `where` is properly supported (including with forced builds and orphan checking), including on resources. 

I'm going to close this PR (sorry) now as I think explicitly adding the `where` if you'd like to do this is better than automagically doing it under the hood. It would probably be good to add more information about how to do that to the wiki though, specifying xPDOCriteria as a YAML array is not the most intuitive format ever ;)

**Pull request closed without merging**
