### PR TITLE
Add Windows wrapper to easily run Gitify on Windows

### PR DESCRIPTION
**Pull request by hansek**

### CODE REVIEW

**Comment by Mark-H** [comment]
This looks interesting. People would just need to run Gitify.cmd instead of php Gitify?

**Comment by hansek** [comment]
Yeap, if they will add path to Gitify folder to their Windows PATH variable.

**Comment by hansek** [comment]
Or better, in Windows you can omit *.cmd* extension and just call `Gitify`

**Comment by Mark-H** [comment]
Nifty, thanks for your help in making Gitify easier to use on windows :)

**Comment by hansek** [comment]
Hope I'll have more time to get "together" path's slashes in code, because those are most problematic on Windows ;)

Thanks Mark, and will let you know about further steps.

**Pull request merged**
