### PR TITLE
Added support for the host parameter in mysqldump

### PR DESCRIPTION
**Pull request by pjona**

### CODE REVIEW

**Comment by mskiba** [comment]
there is something wrong with it?

**Comment by pjona** [comment]
there is something wrong with it?

**Comment by Mark-H** [comment]
Sorry @pjona for not responding to this sooner - nope, it looks good and I'll get this merge in next time I sit down for Gitify which should be this week :)

The `restore` command also needs the host parameter though, right? https://github.com/modmore/Gitify/blob/master/src/Command/RestoreCommand.php#L135

**Comment by pjona** [comment]
Yes, you are right.
I send a second pull request :)

**Comment by Mark-H** [comment]
Awesome, thanks!

**Comment by Mark-H** [comment]
Thanks for your contribution @pjona :)

**Pull request merged**
